In [ ]:
import pandas as pd
import numpy as np


In [3]:
import pandas as pd
import numpy as np

np.arange(0,20).reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
# creat DataFrame

df = pd.DataFrame(data = np.arange(0, 20).reshape(5, 4),
             index = ["Row1", "Row2", "Row3", "Row4", "Row5"],
             columns = ["colunn1", "column2", "column3", "column4"])

In [8]:
df

colunn1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   colunn1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [10]:
# Indexing 
## columnname, rowindex[loc], rowindex, columnindex number[.iloc]
df.head()

colunn1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [12]:
df[['colunn1', 'column2', "column3"]]

colunn1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [13]:
df['column3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: column3, dtype: int32

In [14]:
df.tail()

colunn1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.describe()

colunn1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [22]:
type(df[['colunn1', 'column2', "column3"]])

pandas.core.frame.DataFrame

In [18]:
type(df['column3'])

pandas.core.series.Series

In [23]:
df.loc['Row3']

colunn1     8
column2     9
column3    10
column4    11
Name: Row3, dtype: int32

In [24]:
type(df.loc['Row3'])

pandas.core.series.Series

In [25]:
df.loc[['Row3', 'Row4']]

colunn1  column2  column3  column4
Row3        8        9       10       11
Row4       12       13       14       15

In [26]:
df.iloc[2:4, 0:2]

colunn1  column2
Row3        8        9
Row4       12       13

In [27]:
df.iloc[2:, 1:]

column2  column3  column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [28]:
df.iloc[0:4, 0:3]

colunn1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14

In [33]:
df.iloc[:, ::3]

colunn1  column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [34]:
df.iloc[:, 1:]

column2  column3  column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [35]:
df.iloc[:, 1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [36]:
df.isnull().sum()

colunn1    0
column2    0
column3    0
column4    0
dtype: int64

In [43]:
df = pd.DataFrame(data =[[1, np.nan, 2], [1, 3, 4]],
             index = ["Row1", "Row2"],
             columns = ["column1", "column2", "column3"])

In [44]:
df

column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4

In [45]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [46]:
df.isnull()

column1  column2  column3
Row1    False     True    False
Row2    False    False    False

In [47]:
df.isnull() .sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [48]:
df

column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4

In [52]:
df['column3'].value_counts()

column3
2    1
4    1
Name: count, dtype: int64

In [53]:
df['column3'].unique()

array([2, 4], dtype=int64)

In [54]:
df['column2'].unique()

array([nan,  3.])

In [55]:
df

column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4

In [57]:
df = pd.DataFrame(data = np.arange(0, 20).reshape(5, 4),
             index = ["Row1", "Row2", "Row3", "Row4", "Row5"],
             columns = ["colunn1", "column2", "column3", "column4"])

In [58]:
df

colunn1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [59]:
df['column3'].unique()

array([ 2,  6, 10, 14, 18])

In [60]:
df>2


colunn1  column2  column3  column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True

In [61]:
df['column2']>2

Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Name: column2, dtype: bool

In [62]:
df[df['column2']>2]

colunn1  column2  column3  column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19